In [7]:
#numpy遍历数组（迭代数组）
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
#循环(迭代器对象)
for i in np.nditer(a):
    print(i,end = ' ')

1 2 3 4 5 6 7 8 9 10 

In [11]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

"""
1 2 3
4 5 6
7 8 9
"""

#循环
for i in np.nditer(a):    #默认为order='K'，即照数组原有储存顺序遍历
    print(i,end = " ")

print()

for i in np.nditer(a, order = 'C'):    #默认为order='C'，即,行优先（C 语言风格），横向读取
    print(i,end = " ")

print()

for i in np.nditer(a, order = 'F'):    #默认为order='F'，即,列优先（Fortran 风格），纵向一列一列读取
    print(i,end = " ")

print()

b = np.asfortranarray(a)    #默认储存顺序改为，优先列
for i in np.nditer(b):      #默认为order = "K"，按默认顺序遍历
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 
1 4 7 2 5 8 3 6 9 
1 4 7 2 5 8 3 6 9 

In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

#循环
for i in np.nditer(a,op_flags=['readwrite']):    #遍历还是需要nditer，但原本默认只读
    i[...]=i+1 
    
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [20]:
import numpy as np

a= np.arange(6).reshape(2, 3)
b = np.empty_like(a)

it = np.nditer([a, b], op_flags = [['readonly'], ['writeonly']])
for x, y in it:
    y[...] = x * 2

print(a)
print()
print(b)


[[0 1 2]
 [3 4 5]]

[[ 0  2  4]
 [ 6  8 10]]


In [21]:
#外部循环使用flags
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

for i in np.nditer(a, order = 'F'):
    print(i)
#循环
for i in np.nditer(a,flags=['external_loop'], order = 'F'):
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
4
7
2
5
8
3
6
9
[1 4 7]
[2 5 8]
[3 6 9]


In [35]:
#遍历多个数组
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
b = np.array([1,2,3,4],dtype = int)    #(4, )
print(b)
#广播遍历（广播迭代）
for x,y in np.nditer([a,b]):
    print(f"f({x}) = {y}", end = " | ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[1 2 3 4]
f(0) = 1 | f(5) = 2 | f(10) = 3 | f(15) = 4 | f(20) = 1 | f(25) = 2 | f(30) = 3 | f(35) = 4 | f(40) = 1 | f(45) = 2 | f(50) = 3 | f(55) = 4 | 

In [ ]:
#flatten()与ravel()作为遍历的替代
import numpy as np


In [35]:
#数组相关操作
#numpy相关数组操作（数组变维操作，数组转置操作，修改数组维度操作，连接与分割数组操作）
#1.数组变维操作
#flat函数：返回是一个迭代器，可以用 for 循环遍历其中的每一个元素。
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
for x in a.flat:
    print(x,end = ",")

0,5,10,15,20,25,30,35,40,45,50,55,

In [37]:
#flatten():返回一份数组副本，对副本修改不会影响原始数组
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
print(a.flatten())

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [38]:
#ravel():返回一份数组视图，对修改修改是会影响原始数组
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
print(a.ravel())

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0  5 10 15 20 25 30 35 40 45 50 55]


In [41]:
#2.数组转置操作
#1.transpose:将数组的维度值进行对换，比如二维数组维度(2,4)使用该方法后为(4,2)
import numpy as np
a = np.arange(12).reshape(3,4)
print (np.transpose(a))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [41]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)

print()

print(np.transpose(a))

print()

print (a.T)   #此为.transpose()的简写。a.T相当于a^T，可以说是非常直观了。与数学写法一致

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [45]:
import numpy as np
a = np.arange(4).reshape(1,4)
print(a)
print()
b = np.arange(12).reshape(3,4)
print(b)
print()
print(a * b)
print()
print(np.broadcast_to(a,(5,4)))

[[0 1 2 3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [51]:
import numpy as np
a = np.arange(4).reshape(1,4)
print(a)
b = np.squeeze(a)
print(b)

[[0 1 2 3]]
[0 1 2 3]


In [52]:
#连接与分割数组操作
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
print()
b = np.array([[5,6],[7,8]])
print(b)
print()

print(np.concatenate((a,b),axis = 0))#0垂直方向
print()
print(np.concatenate((a,b),axis = 1))#1水平方向
print("————————————")

#vstack和hstack属于是对于ndim<=2（axis < 2）的多维数组来看，只有行和列，作为对轴写法的简写
#但对于更高维的数组，用axis指明方向是必需的。即：axis越大越是数组内层，越小越是数组外层

print(np.vstack((a,b)))#v垂直拼，按行拼，等价于axis = 0    vertical-垂直的
print()
print(np.hstack((a,b)))#h水平拼，按列拼，等价于axis = 1    horizontal-水平的

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]
————————————
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
print()
b = np.array([[5,6],[7,8]])
print(b)
print()

print(np.vstack((a,b)))#h列方向，v行方向    vertical-垂直的
print()
print(np.hstack((a,b)))#h列方向，v行方向    horizontal-水平的

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [65]:
import numpy as np
a = np.arange(10)
print(a)

#分割
b = np.split(a,2)
print(b)

c = np.array([[[1,2],[1,3],[3,3]],
              [[4,5],[2,5],[27,3]],
              [[0,0],[7,7],[8,8]]])
num = c.shape
print(num)

d = np.split(c,3)    #原本(3,3,2)，切分为(1,3,2)。很明显，对axis = 0（数组最外层）切分，自然是改第一个数，分成三个一。注：据此可知，未声明时默认切最外层，即沿axis=0的方向
print(d)
e = np.split(c,3, axis = 1)    #原本(3,3,2)，切分为(3,1,2)。很明显，对axis = 1（数组第二层）切分，自然是改第二个数，分成三个一。
print(e)


[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
(3, 3, 2)
[array([[[1, 2],
        [1, 3],
        [3, 3]]]), array([[[ 4,  5],
        [ 2,  5],
        [27,  3]]]), array([[[0, 0],
        [7, 7],
        [8, 8]]])]
[array([[[1, 2]],

       [[4, 5]],

       [[0, 0]]]), array([[[1, 3]],

       [[2, 5]],

       [[7, 7]]]), array([[[ 3,  3]],

       [[27,  3]],

       [[ 8,  8]]])]
