In [4]:
import numpy as np
a = np.array([[[1,2],[1,3],[4,3]],
              [[4,1],[2,5],[27,3]],
              [[0,78],[7,5],[8,8]]])
print(a)
print(a.shape)

print(np.sort(a))    #不写方向，就默认排序最后一个轴
print("————————")
print(np.sort(a, axis = 0))    #大块自然没法直接一起比，但明显可以对应位置一一比对，这里明显以二维数组为单位
#所以拿(0,0,0)比(1,0,0)比(2,0,0)以此类推
print("——————")
print(np.sort(a,  axis = 1))

#注：np.sort()返回副本，不会修改原数组

[[[ 1  2]
  [ 1  3]
  [ 4  3]]

 [[ 4  1]
  [ 2  5]
  [27  3]]

 [[ 0 78]
  [ 7  5]
  [ 8  8]]]
(3, 3, 2)
[[[ 1  2]
  [ 1  3]
  [ 3  4]]

 [[ 1  4]
  [ 2  5]
  [ 3 27]]

 [[ 0 78]
  [ 5  7]
  [ 8  8]]]
————————
[[[ 0  1]
  [ 1  3]
  [ 4  3]]

 [[ 1  2]
  [ 2  5]
  [ 8  3]]

 [[ 4 78]
  [ 7  5]
  [27  8]]]
——————
[[[ 1  2]
  [ 1  3]
  [ 4  3]]

 [[ 2  1]
  [ 4  3]
  [27  5]]

 [[ 0  5]
  [ 7  8]
  [ 8 78]]]


In [9]:
import numpy as np
# 结构化数组排序示例
dt = np.dtype([('name','S10'),('age',int)])    #设定一个结构或是说组合，再以其中的某个值为依据排序
arr = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype=dt)    #以dtype设好的格式以元组的形式作为元素，创建相关的数组
print(np.sort(arr, order='name')) # 根据name字段排序

[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [13]:
import numpy as np
a = np.array(['a','e','r','b','u','v'])
b = np.array([34,12,34,7,7,7])
ind = np.lexsort((a,b))    #越靠后优先级越高，如，此处便以b（数字）为主键，a（字母）为次键
for i in ind:
    print(a[i],b[i])

b 7
u 7
v 7
e 12
a 34
r 34


In [20]:
import numpy as np
a = np.zeros(18).reshape(3,2,3)
print(a.nonzero())    #没有则返回空数组
b = np.arange(36).reshape(2,3,2,3)
c = np.broadcast_to(a,(1,3,2,3))
print(np.insert(b,2,c,axis = 0).nonzero())                 

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]), array([0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))


In [21]:
import numpy as np
b = np.array([12, 90, 380, 12, 211])
print(np.where(b>12)) # 返回索引 (array([1, 2, 4]),)

# 三参数用法：满足条件取1，不满足取0
res = np.where(b>12,1,0)    #很像三元运算符：b > 12 ? 1 : 0
print(res)

(array([1, 2, 4]),)
[0 1 1 0 1]


In [27]:
import numpy as np
x = np.arange(9.).reshape(3, 3)
cond = np.mod(x,2)==0 # 判断偶数
print(np.extract(cond, x)) # [0. 2. 4. 6. 8.]
print(x.dtype)

[0. 2. 4. 6. 8.]
float64


In [34]:
import numpy as np
a = np.array([[30,40,70],[80,20,10],[50,90,60]])
print(np.argmax(a)) #全部展平，最大值下标：7
print(np.argmax(a,axis=0)) #按列找最大值索引
print(np.argmax(a,axis=1)) #按行找最大值索引
print("-------")
print(a[np.argmax(a,axis=1),np.argmax(a,axis=0)])
print(a.flatten()[np.argmax(a)])

7
[1 2 0]
[2 0 1]
-------
[90 70 80]
90
