In [ ]:
import numpy as np 
a = np.array([1,2,3])#ndmin：设置数组对象的维度
print(a.ndim)#查看数据组对象维度：ndim

In [ ]:
import numpy as np 
a = np.array([1,2,3])#ndmin：设置数组对象的维度
print(a.ndim)#查看数据组对象维度：ndim

In [ ]:
import numpy as np 
a = np.array([1,2,3])#ndmin：设置数组对象的维度
print(a.ndim)#查看数据组对象维度：ndim

In [14]:
#reshape数组变维
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
a = a.reshape(2,3)#变维
print(a)#2*3

[[1 2 3]
 [4 5 6]]


In [18]:
import numpy as np 
a = np.array([1,2,3],dtype = int)
print(a)

[1 2 3]


In [19]:
#NumPy数据类型
#数据类型对象:dtype
import numpy as np 
#使用了标量类型
a = np.dtype(np.int32)
print(a)

int32


In [21]:
#数据类型对象:dtype
import numpy as np 
#使用了标量类型
a = np.dtype('i4')
print(a)

int32


In [27]:
#定义结构化数据
import numpy as np 
a = np.dtype([('name','U20'),('age','i4')])
b = np.array([('张三',123),('李四',1)],dtype = a)
print(b)

[('张三', 123) ('李四',   1)]


In [28]:
#NumPy 数组属性（ndarray）
import numpy as np 
a = np.array([1,2,3])#ndmin：设置数组对象的维度
print(a.ndim)#查看数据组对象维度：ndim

1


In [30]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)#查看数组形状

(2, 3)


In [10]:
import numpy as np 
a = np.array([1,2,3])
b = 10
print(np.shape(a))
print(np.shape(b))
print(type(a.shape))
print(np.shape(a + b))

(3,)
()
<class 'tuple'>
(3,)


In [32]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
a.shape = (6,1)#可以调整数组大小
print(a)#查看数组形状

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [33]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a.size)#长度数

6


In [35]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a.dtype)

int32


In [1]:
#flags
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a.data)

In [39]:
#Numpy创建数组
#empty：会生成随机数(未被初始化的时候会随机生成元素值)
import numpy as np
a = np.empty([3,3],dtype = int)
print(a)

[[       0     1236        5]
 [73895936        0   131079]
 [73764704        0        5]]


In [40]:
#zeros()：创建指定大小数组元素以0来填充
import numpy as np
a = np.zeros([3,3],dtype = int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [41]:
#题目 1
#创建一个长度为 5 的一维数组，元素全为 0（默认数据类型）
import numpy as np
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [42]:
#ones()
import numpy as np
a = np.ones([3,3],dtype = int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [45]:
#asarray()#转化成ndarray
import numpy as np
a = [1,2,3,4,5,6,7,8,9]
c = np.asarray(a)
print(type(c))

<class 'numpy.ndarray'>


In [1]:
#frombuffer()
import numpy as np
h = b'hello numpy'#转成成ndarray:(bytes)转成成str
a = np.frombuffer(h,dtype = "S1")
print(a)#流

[b'h' b'e' b'l' b'l' b'o' b' ' b'n' b'u' b'm' b'p' b'y']


In [60]:
#fromiter()：可以把迭代对象转换成ndarray
a = [1,2,3,4,5,6]
it = iter(a)#将列表转换成迭代器
print(it)

b = np.fromiter(it,dtype = int)#从迭代器当中去读取元素
print(b)

[1 2 3 4 5 6]


In [5]:
#arrange(n)依次输入[0,n)，再用reshape()确定形状
import numpy as np
c = np.arange(24).reshape(4, 3, 2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
