In [5]:
#numpy数组的元素增删改查
#1.返回指定形状的新数组。
import numpy as np

a = np.array([[1,2,3],[4,5,6]])    #(2,3)
print(a)
print(a.shape)
print()

#指定形状的新数组(改)
print(np.resize(a,(3,2)))    #大小一样时自然就相当于reshape()，
print()
print(np.resize(a,(2,6)))    #但是，新形状更大，自然以原本的元素重复填充
print()
print(np.resize(a,(2,1)))    #反之，会依次录入，有一种截断的效果

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

[[1]
 [2]]


In [31]:
#2.将元素值添加到数组的末尾
import numpy as np

a = np.array([[1,2,3],[4,5,6]])    #(2,3)
print(a)
print(a.shape)

#向数组末尾添加元素（增）
print(np.append(a,[[10,11,12]],axis = 0))    #如结果所示：0为在行末尾向下横着加，只有axis=0这个轴可以随便取值  (1,3)
print(np.append(a,[[10,11,12]],axis = 0).shape)
print(np.append(a,[[7,8],[10,11]],axis = 1))    #如结果所示：1为在列末尾向右横着加，只有axis=1这个轴可以随便取值 (2,2)
print(np.append(a,[[7,8],[10,11]],axis = 1).shape)
print(np.append(a,[[[1],[2]]],axis=None))    #axis=None时完全展平为一维再追加，甚至维度都无所谓了
#注：首先ndim必须完全一致。其次对应轴方向以外的轴，上的数字一定要一致，而对应轴则无要求。结果自然就是对应轴原有的值加上自由加的值了
print("b:")
b = np.array([[[1,2],[1,3],[3,3]],
              [[4,5],[2,5],[27,3]],
              [[9,9],[7,7],[8,8]]])
print(b)
print(b.shape)   #(3,3,2)

print(np.append(b,np.zeros(12).reshape(2,3,2),axis = 0))    #如结果所示：0为在行末尾向下横着加，只有axis=0这个轴可以随便取值  (2,3,3)
print("——————") #结果自然是(3,3,2)+(2,3,2)->(沿axis=0)为(3+2,3,2)=(5,3,2)。其他同理
print(np.append(b,np.zeros(6).reshape(3,1,2),axis = 1))    #如结果所示：1为在列末尾向右横着加，只有axis=1这个轴可以随便取值 (3,1,2)

#注：更重要的是，append返回新数组，而不修改原数组。

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
(3, 3)
[[ 1  2  3  7  8]
 [ 4  5  6 10 11]]
(2, 5)
[1 2 3 4 5 6 1 2]
b:
[[[ 1  2]
  [ 1  3]
  [ 3  3]]

 [[ 4  5]
  [ 2  5]
  [27  3]]

 [[ 9  9]
  [ 7  7]
  [ 8  8]]]
(3, 3, 2)
[[[ 1.  2.]
  [ 1.  3.]
  [ 3.  3.]]

 [[ 4.  5.]
  [ 2.  5.]
  [27.  3.]]

 [[ 9.  9.]
  [ 7.  7.]
  [ 8.  8.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
——————
[[[ 1.  2.]
  [ 1.  3.]
  [ 3.  3.]
  [ 0.  0.]]

 [[ 4.  5.]
  [ 2.  5.]
  [27.  3.]
  [ 0.  0.]]

 [[ 9.  9.]
  [ 7.  7.]
  [ 8.  8.]
  [ 0.  0.]]]


In [3]:
#3.沿规定的轴将元素值插入到指定的元素前。 （插队）
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
#行索引         0     1     2     3     4
print(a.shape)
print(a)

#在指定索引位置前面插入数据（插队）
print(np.insert(a,3,[66,66],axis = 0))
print(np.insert(a,3,[66,66],axis = 0).shape)    #(5+1,2)，因此就是在对应轴上插入，依旧注意其他轴需要数一致

b = np.ones(36).reshape(2,3,6)
print(b.shape)
print(np.insert(b,0,np.zeros(24).reshape(2,2,6),axis = 1))
print(np.insert(b,0,np.zeros(24).reshape(2,2,6),axis = 1).shape)

(5, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [66 66]
 [ 7  8]
 [ 9 10]]
(6, 2)
(2, 3, 6)
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
(2, 5, 6)


In [19]:
#argwhere(条件的筛选)了解即可
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(a)

#返回所有大于1的元素索引
b = np.argwhere(a>1)
print(b)

for

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[0 1]
 [1 0]
 [1 1]
 [2 0]
 [2 1]
 [3 0]
 [3 1]
 [4 0]
 [4 1]]


In [4]:
#删掉某个轴上的子数组，并返回删除后的新数组。
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
#索引          0 1   2  3  4 5   6  7  8  9
print(a)
print(a.shape)

#删除(指定元素的索引)
print(np.delete(a,1,axis = 0))#删除行数据（0,行数数据,1列数数据）
print(np.delete(a,1,axis = 0).shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(5, 2)
[[ 1  2]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
(4, 2)


In [29]:
#用于删除数组中重复的元素，并按元素值由大到小返回一个新数组。
import numpy as np

a = np.array([5,2,6,2,7,5,6,8,2,9])
print(a)

#对a数组去除重复元素(什么是属于重复元素？？，答案：超过第一次出现的都是重复元素)
b = np.unique(a)
print(b)

[5 2 6 2 7 5 6 8 2 9]
[2 5 6 7 8 9]


In [31]:
#NumPy位运算（二进制计算）
import numpy as np
a = 10 # 1010
b = 12 # 1100
print("10的二进制是：",bin(a))
print("12的二进制是：",bin(b))

10的二进制是： 0b1010
12的二进制是： 0b1100


In [32]:
import numpy as np
a = 10 # 1010
b = 12 # 1100
print("10的二进制是：",bin(a))
print("12的二进制是：",bin(b))
# 与 运算
#与运算（&）： 对应位上的两个数字都为1时，结果为1；否则，结果为0。
#例如：1010 & 1100 = 1000
print(np.bitwise_and(a,b))#1000

10的二进制是： 0b1010
12的二进制是： 0b1100
8


In [35]:
#左移运算（<<）：** 将数字的所有位向左移动指定的位数，右侧用0填充。
a = 10 # 1010
#左移3步在运算(移动了几位就添加几个0)
print(np.left_shift(a,3))
101000

80


101000

In [36]:
#字符串函数
import numpy as np 
a = 'hello'
b = 'Python'
print(np.char.add(a,b))

helloPython


In [37]:
import numpy as np 
a = 'hello'
print(np.char.multiply(a,5))

hellohellohellohellohello


In [41]:
import numpy as np 
a = 'hello'
print(np.char.center(a,10,fillchar = '8'))

88hello888


In [42]:
#将字符串第一个字母转换为大写。
import numpy as np 
a = 'hello'
print(np.char.capitalize(a))

Hello


In [43]:
import numpy as np 
a = 'hello python go go'
print(np.char.title(a))

Hello Python Go Go


In [44]:
import numpy as np 
a = 'HELLO'
print(np.char.lower(a))

hello


In [45]:
import numpy as np 
a = 'hello'
print(np.char.upper(a))

HELLO


In [48]:
#字符切割
import numpy as np 
a = 'hello1python1go go'
print(np.char.split(a,sep ='g'))

['hello1python1', 'o ', 'o']


In [7]:
import numpy as np 
a = 'hello\npython|1_go g\to'
print(np.char.splitlines(a))

['hello', 'python|1_go g\to']


In [53]:
import numpy as np 
a = 'hello666'
print(np.char.replace(a,'ll','cc'))

hecco666


In [58]:
#解码和编码（开锁和上锁）
# utf-8，cp500 
a = '123654'#银行卡密码
#编码
c = np.char.encode(a,'cp500') 
print(c)
#解码
print(np.char.decode(c,'cp500'))

b'\xf1\xf2\xf3\xf6\xf5\xf4'
123654
