In [5]:
#索引和切片（获取数据的）
import numpy as np
#一维数组下标获取数据元素
a = np.array([1,2,3,4,5,6])
#下标         0 1 2 3 4 5
print(a[1])

2


In [6]:
#二维数组下标获取数据元素
import numpy as np
a = np.array([[1,2],[3,4]])#2*2
print(a[1,0])

3


In [7]:
#条件获取多元素数据
import numpy as np
#一维数组下标获取数据元素
a = np.array([1,2,3,4,5,6])
#下标         0 1 2 3 4 5
#生成切片对象
s = slice(1,4)#起始索引，终止索引(包前不包后)，步长
print(a[s])

[2 3 4]


In [15]:
import numpy as np
#一维数组下标获取数据元素
a = np.array([1,2,3,4,5,6])
#关键符号冒号：
print(a[1:4:2])#起始索引，终止索引(包前不包后)，步长

[2 4]


In [17]:
import numpy as np
#一维数组下标获取数据元素
a = np.array([1,2,3,4,5,6])
#关键符号冒号：
print(a[1:3])#起始索引，终止索引(包前不包后)，步长

[2 3]


In [20]:
#多维数组切片
import numpy as np
#一维数组下标获取数据元素
a = np.array([[1,2,3],[4,5,6]])
print(a[0:])#默认是按照行索引切片的

[[1 2 3]
 [4 5 6]]


In [23]:
#按照列索引切片
#多维数组切片
import numpy as np
#一维数组下标获取数据元素
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
#列索引切片...
print(a[...,1:])#省略号在前表示：列，在后表示：行

[4 5 6]


In [4]:
#高级索引
#1.整数数组索引
import numpy as np
#创建二维数组
a = np.array([[1,2],[3,4],[5,6]])#3行2列
y = a[[1,1,2],[0,1,0]]#先获取行索引，再获取列索引
print(y)

print()

z = a[[2,0,1]]
print(z)

[3 4 5]

[[5 6]
 [1 2]
 [3 4]]


In [28]:
#1.整数数组索引
import numpy as np
b = np.array([[ 0, 1, 2],
              [ 3, 4, 5],
              [ 6, 7, 8],
              [ 9,10,11]])

r = np.array([[0,0],[3,3]])#保存行索引
c = np.array([[0,2],[0,2]])#保存列索引
#获取四个角的元素
d= b[r,c]
print(d)

[[ 0  2]
 [ 9 11]]


In [32]:
#布尔索引
import numpy as np
#创建二维数组
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
#使用布尔索引机制
print(a[a > 3])

[3 3]


In [4]:
#布尔索引针对特定轴筛选
import numpy as np
a = np.array([[[1,2],[1,3],[3,3]],
              [[4,5],[2,5],[27,3]],
              [[0,0],[7,7],[8,8]]])
print("原数组：")
print(a)
#比如我想把axis=2的一部分删了（此处为删除第二个数），即第三个索引取放mark，第二个标记为False，最小的单元要删去

mark = [True, False]    #一定注意数量与对应轴上的数一致，如此处数组a.shape = (3, 3, 2)，最内层是两个元素
result = a[..., mark]    #[axis = 0, axis = 1, axis = 2] 最外层（小数） -> 最内层（大数）
print("result:")
print(result)

#把axis= 0全删了，可以用mark = [False, True, True]
#（或用上面整数那个索引（花式索引），写作y = a[[1,2]],同y = a[[1,2],...]
y = a[[1,2]]    #即a[[1,2],...],即取出索引为1和2的两行，并对元素无要求
print("y:")
print(y)

d = a[..., [0]]
print("d:")
print(d)

原数组：
[[[ 1  2]
  [ 1  3]
  [ 3  3]]

 [[ 4  5]
  [ 2  5]
  [27  3]]

 [[ 0  0]
  [ 7  7]
  [ 8  8]]]
result:
[[[ 1]
  [ 1]
  [ 3]]

 [[ 4]
  [ 2]
  [27]]

 [[ 0]
  [ 7]
  [ 8]]]
y:
[[[ 4  5]
  [ 2  5]
  [27  3]]

 [[ 0  0]
  [ 7  7]
  [ 8  8]]]
d:
[[[ 1]
  [ 1]
  [ 3]]

 [[ 4]
  [ 2]
  [27]]

 [[ 0]
  [ 7]
  [ 8]]]


In [37]:
import numpy as np#(了解即可)
a = np.array([1,2,3,np.nan,5])
print(a[~np.isnan(a)])

[1. 2. 3. 5.]


In [42]:
#删除整数元素(了解即可)
import numpy as np
a = np.array([1,2+6j,3,4+1j,5])
print(a[np.iscomplex(a)])

[2.+6.j 4.+1.j]


In [46]:
#花式索引
import numpy as np
#一维数组
a = np.array([1,2,3,4,5,6])
print(a)
#使用花式索引
b = a[[1,2]]
print(b)

#形成了一个副本
print(b[0])
print(b[1])

[1 2 3 4 5 6]
[2 3]
2
3


In [48]:
#广播机制
a = np.array([1,2,3])#一行3列,a.shape = (3, )
b = np.array([10,20,30])#一行3列,b.shape = (3, )
#满足对照关系就可以计算
print(a * b)

[10 40 90]


In [3]:
a = np.array([1,2,3])#一行3列,shape(a) = (3, )
b = np.array([[10],[20],[30],[30],[10]])#一行3列, b.shape = (5, 1)
#触发广播机制
print(np.shape(a))
print(np.shape(b))
print(np.shape(a+b)) #a先补全维度，补1于外侧，即形状左边，(1, 3)。再对齐具体数字，即(5, 3)
print(a + b)

(3,)
(5, 1)
(5, 3)
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [31 32 33]
 [11 12 13]]


In [11]:
a = np.array([1,2,3,4])#一行3列,a.shape = (4, )
b = np.array([[1,2,3,4],[1,2,3,4]])#一行4列,b.shape = (2, 4)
#触发广播机制 ,补成(2,4)
print(a + b)

[[2 4 6 8]
 [2 4 6 8]]


In [8]:
import numpy as np
a = np.array([[1],
              [2],
              [3]])    #a.shape = (3, 1)
b = np.array([10, 20, 30, 40])    #shape(b) = (4, )

c = a + b
d = a * b

print(c.shape)

print(c)

print()

print(d)    #此时这里就是外积了 

"""
    1 1 1 1            10 20 30 40
    2 2 2 2            10 20 30 40
    3 3 3 3            10 20 30 40
(3,1) -> (3,4)    (4,)->(1,4)->(3,4)

明显对应位置相乘，恰好符合了外积的运算规律
即新矩阵d34 = 120 = 3 * 40 = m34 * n34 = a3 * b4
"""

(3, 4)
[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]]


In [7]:
#只有数字一能扩，即一行或一列
import numpy as np
a = np.ones((2,3))
b = np.ones((3)) #4就不行了，即(1,4) 与 (2,3), 一是能扩成2，但3是不能扩的
print(a + b)

[[2. 2. 2.]
 [2. 2. 2.]]
